version: '3'

networks:
  my_network:

services: 
  apigateway:
    image: setupcopy/searchengineer
    ports:
      - "5000:80"
    networks:
      - my_network

  searchservice:
    image: setupcopy/searchengineerbff
    ports:
      - "5050:80"
    networks:
      - my_network
    environment:
      - SearchEngineerUrl=http://apigateway:80

